[build]
  command = "npm run build"
  publish = ".next"

[functions."*.js"]
  timeout = 60

[functions."*/route.js"]
  timeout = 60

[functions."**/*.js"]
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-nextjs"
